version: "3.8"
services:
   app:
      build: app/
      links:
         - mysql
      ports:
        - 5000:5000
   ##https://stavshamir.github.io/python/dockerizing-a-flask-mysql-app-with-docker-compose/ , https://medium.com/@shamir.stav_83310/dockerizing-a-flask-mysql-app-with-docker-compose-c4f51d20b40d
   mysql:
      image: mysql:5.7   # this is a base image
      ports:
         - 32000:3306    # map port 32000 of the host to the port 3306 of th4e mysql
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro  #initialize the mysql schema from the sql file we have
        - todo-mysql-data:/var/lib/mysql
      environment: 
         MYSQL_DATABASE: netbackup              # this is the database we want to create
         MYSQL_ROOT_PASSWORD: Gyp.s8m           # this the password we want to create for the user root of the mysql
   web:                                         #https://www.programials.com/docker-run-static-website
    image: nginx                                # use nginx as the base image
    volumes: 
      - ./static:/usr/share/nginx/html          # mount volume from the current direcotory into the the public folder of the nginx so that any changes locally is reflected immeditely in the server
    container_name: illuminate-quiz             # use this as the container name
    restart: always                             # restart the server always
    ports:   
      - 8081:80                                 # map port 8081 of the host to the port 80 of the container
volumes:
   todo-mysql-data:
